API_HOST_URL: 'http://staging.learn.proversity.io'
OAUTH_CLIENT_ID: 'feed7f34667e8799b244'
ENVIRONMENT_DISPLAY_NAME: 'Staging'
PLATFORM_NAME: 'Staging'
PLATFORM_DESTINATION_NAME: 'Staging'
FEEDBACK_EMAIL_ADDRESS: 'support@proversity.org'
DEBUG: false
ORGANIZATION_CODE: 'edX'
PUSH_NOTIFICATIONS: true
KONNEKTEER_API_KEY: ''
COURSE_ENROLLMENT:
  ENABLED: true
  TYPE: 'native'
  COURSE_SHARING_ENABLED: false
DISCUSSIONS_ENABLED: true
CERTIFICATES_ENABLED: true
USER_PROFILES_ENABLED: true
BADGES_ENABLED: true
REGISTRATION_ENABLED: true
SEGMENT_IO:
  SEGMENT_IO_WRITE_KEY: ''
  ENABLED: false
LINKEDIN:
  ENABLED: true
  GET_PROFILE: true