# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
 "iPhone 6 Plus"
])

languages([
  "en-US"
  # "de-DE",
  # "it-IT",
  # ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme "edX"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true
skip_open_summary true
reinstall_app true
erase_simulator true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./edX.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
